### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Miguimonti** [Aktyn/BertaSnakes#1]
Hello
Good morning, I would like to contribute to the project by providing a logo without commitment.
Let me know if you want me to submit any proposal.

Cheers!

**Comment by Aktyn** [comment]
Hi
This is project of BertaSnakes logo although it is not included anywhere on the page yet.
![logo](https://user-images.githubusercontent.com/22148918/61450172-ccd05e00-a956-11e9-9ece-d0c74a6b5839.png)
If you got already prepared some nice logo design then I would like to see it and maybe choose it as current one.
