### ISSUE TITLE
Not able to run server

### ISSUE THREAD

**Issue by akzhol0921** [Aktyn/BertaSnakes#26]
![image](https://user-images.githubusercontent.com/43620746/125598528-e11875d9-0d39-4651-9839-915180d1436c.png)

**Comment by Aktyn** [comment]
Build client to generate files for server to share on it's rest api port.
`npm run client:build`

After that this error shouldn't occur although you could still start project in dev mode despite this error.

**Comment by akzhol0921** [comment]
Got ya, what is OPENEXCHANGE_APP_ID means here?

**Comment by Aktyn** [comment]
> Got ya, what is OPENEXCHANGE_APP_ID means here?

It's external API for calculating cryptocurrency rates.
You'll find it's usage in this file: https://github.com/Aktyn/BertaSnakes/blob/master/sources/server/currencies.ts
You can generate API key on their [site](https://openexchangerates.org/) and pass it just like other parameters while running server.
