### ISSUE TITLE
Failed to compile client and server

### ISSUE THREAD

**Issue by akzhol0921** [Aktyn/BertaSnakes#27]
![image](https://user-images.githubusercontent.com/43620746/125731566-3aa8be1a-5c47-41c6-897f-b3f74821e789.png)

![image](https://user-images.githubusercontent.com/43620746/125731548-037a09f6-3f42-4f2a-aeab-477407bf86c9.png)

what is this problem?

**Comment by Aktyn** [comment]
I think you're trying to compile project using incompatible version of typescript or done some bad changes to the code.
